_target_: instant_avatar.datasets.monocap_dataset.MonoCapDataModule
name: monocap
subject: animation
gender: neutral 
opt:
  dataroot: /data2/zhiyh/MonoCap_processed/vlad_images1011
  subject: ${dataset.subject}
  dmtet_geo_path: ./data/SMPLX/tets/smpl_tets.obj
  train:
    view_id: [66]
    num_workers: 8
    batch_size: 1
    start: 1
    end: 500 
    skip: 5
    downscale: 2
    sampler: ${sampler}
    fitting: ${model.opt.optimize_SMPL.enable}
    refine: ${model.opt.optimize_SMPL.is_refine}
    white_background: False 
    random_init: True
    processed: True
  val:
    view_id: [66] 
    num_workers: 4
    batch_size: 1
    start: 451 
    end: 461 
    skip: 4 
    downscale: 2 
    white_background: false
    random_init: True
    processed: True
  test:
    view_id: [0,10,20,30,40,50,60,70,80,90,100]
    num_workers: 4
    batch_size: 1
    start: 1 
    end: 510 
    skip: 30 
    downscale: 2 
    white_background: false
    random_init: True
    processed: True
